services:
  postgres:
    image: postgres:17.0-alpine
    environment:
      - POSTGRES_USER=arbibot
      - POSTGRES_PASSWORD=arbibot123
      - POSTGRES_DB=arbibot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U arbibot" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
