services:
  bot:
    build: ./server
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=arbibot
      - POSTGRES_PASSWORD=arbibot123
      - POSTGRES_DB=arbibot
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./server/cache:/app/cache
    develop:
      watch:
        - action: rebuild
          path: ./server/src
          target: /app
          ignore:
            - node_modules/

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - bot
    environment:
      - VITE_API_URL=http://localhost:3000
    develop:
      watch:
        - action: rebuild
          path: ./client
          target: /app
          ignore:
            - ./client/node_modules/

  postgres:
    image: postgres:17.0-alpine
    environment:
      - POSTGRES_USER=arbibot
      - POSTGRES_PASSWORD=arbibot123
      - POSTGRES_DB=arbibot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U arbibot" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
